postgresql:
  host: localhost
  port: 5432
  db: website_dev
  user: root
  password: 926453
  log-level: dev
logger:
  level: info
  prefix: "[website]"
  director: log
  show-line: true
  log-in-console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
